# Generated by Django 5.2.7 on 2025-12-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "heart_charity",
            "0004_receiptsequence_donation_branch_donation_deleted_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
